sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
script:
  - npm run clean
  - npm run build
  - npm run lint
  - npm run test:cover
after_script:
  - npm run test:report
  - npm run docs:deploy
branches:
  only:
    - master
cache:
  directories:
    - node_modules
