sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
script:
  - npm run clean
  - npm run build
  - npm run lint
  - npm run test:cov
after_script:
  - npm run coveralls
branches:
  only:
    - master
    - dev
cache:
  directories:
    - node_modules
