#!/usr/bin/env bash
set -e

PATH=$(npm bin):$PATH
ROOT_DIR=$(cd $(dirname $0)/..; pwd)

cd $ROOT_DIR/docs

sed '1i\
---\
title: Change Log\
layout: page\
notes: This file is autogenerated by CHANGELOG.md file in root directory. Do not edit this file.\
---\
\
' $ROOT_DIR/CHANGELOG.md ./source > ./source/CHANGELOG.md
